package cz.itstep;

public class StringPractice {

    public static void main(String[] args) {
        String input = "Hello World!";
//        String input = longText();

        long str, end;

        str = System.nanoTime();
        StringBuilder sb = new StringBuilder();
        int inputLength = input.length();
        for (int i = 0; i < inputLength; i++) {
            char c = input.charAt(inputLength - i - 1);
            sb.append(c);
        }
        end = System.nanoTime();


        System.out.println("time=" + (end - str) + " ");
        System.out.println(sb.toString());

        str = System.nanoTime();
        String reversed = new StringBuilder(input).reverse().toString();
        end = System.nanoTime();

        System.out.println("time=" + (end - str) + " ");
        System.out.println(reversed);

    }

    public static String longText() {
        return "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Etiam neque. Aenean vel massa quis mauris vehicula lacinia. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. In dapibus augue non sapien. In enim a arcu imperdiet malesuada. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Fusce consectetuer risus a nunc. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Quisque porta. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.\n" +
                "\n" +
                "Aliquam erat volutpat. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Donec vitae arcu. Etiam commodo dui eget wisi. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Praesent dapibus. Nullam at arcu a est sollicitudin euismod. Vivamus ac leo pretium faucibus.\n" +
                "\n" +
                "Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Nullam sit amet magna in magna gravida vehicula. Fusce wisi. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Phasellus rhoncus. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Pellentesque ipsum. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Aliquam ante. Et harum quidem rerum facilis est et expedita distinctio. Quisque tincidunt scelerisque libero. Etiam dictum tincidunt diam. Curabitur sagittis hendrerit ante. Proin mattis lacinia justo. Integer lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nulla non lectus sed nisl molestie malesuada. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.\n" +
                "\n" +
                "Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer tempor. Duis pulvinar. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Aenean vel massa quis mauris vehicula lacinia. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc tincidunt ante vitae massa. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Praesent in mauris eu tortor porttitor accumsan. Proin in tellus sit amet nibh dignissim sagittis. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Nullam at arcu a est sollicitudin euismod. Integer tempor. Suspendisse nisl. Phasellus rhoncus. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum.\n" +
                "\n" +
                "Aliquam erat volutpat. Fusce wisi. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Suspendisse nisl. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Sed convallis magna eu sem. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Cras elementum. Ut tempus purus at lorem. Fusce consectetuer risus a nunc. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Proin mattis lacinia justo. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Etiam dictum tincidunt diam.\n" +
                "\n" +
                "Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Aliquam in lorem sit amet leo accumsan lacinia. Maecenas lorem. Aliquam erat volutpat. Nam sed tellus id magna elementum tincidunt. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Vivamus luctus egestas leo. Suspendisse nisl. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Pellentesque sapien. Curabitur vitae diam non enim vestibulum interdum. In dapibus augue non sapien. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Integer in sapien.\n" +
                "\n" +
                "Cras elementum. Etiam dictum tincidunt diam. Praesent in mauris eu tortor porttitor accumsan. Nulla est. Nam quis nulla. Nunc dapibus tortor vel mi dapibus sollicitudin. Nulla non arcu lacinia neque faucibus fringilla. Fusce wisi. Aliquam erat volutpat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. In enim a arcu imperdiet malesuada. Integer in sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Maecenas sollicitudin.\n" +
                "\n" +
                "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Nullam faucibus mi quis velit. Fusce tellus. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Pellentesque sapien. Nullam eget nisl. Integer malesuada. Phasellus faucibus molestie nisl. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Aliquam id dolor.\n" +
                "\n" +
                "Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer lacinia. Aliquam erat volutpat. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus faucibus molestie nisl. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Maecenas sollicitudin. In enim a arcu imperdiet malesuada. Praesent id justo in neque elementum ultrices.\n" +
                "\n" +
                "Sed ac dolor sit amet purus malesuada congue. Fusce nibh. Nam sed tellus id magna elementum tincidunt. Nullam dapibus fermentum ipsum. Nulla quis diam. Nullam faucibus mi quis velit. In enim a arcu imperdiet malesuada. Aenean placerat. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Curabitur bibendum justo non orci. Suspendisse nisl. Integer pellentesque quam vel velit. Mauris tincidunt sem sed arcu.\n" +
                "\n" +
                "Duis condimentum augue id magna semper rutrum. Proin mattis lacinia justo. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Integer in sapien. Maecenas lorem. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Duis condimentum augue id magna semper rutrum. Aenean placerat. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris elementum mauris vitae tortor. Maecenas sollicitudin. Aenean placerat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce suscipit libero eget elit. Nullam at arcu a est sollicitudin euismod. Aliquam in lorem sit amet leo accumsan lacinia.\n" +
                "\n" +
                "Nullam faucibus mi quis velit. Aliquam id dolor. Nullam rhoncus aliquam metus. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Aliquam ante. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Aenean id metus id velit ullamcorper pulvinar. Nullam eget nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Integer vulputate sem a nibh rutrum consequat. Vivamus luctus egestas leo. Etiam dictum tincidunt diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Nullam sit amet magna in magna gravida vehicula. Maecenas aliquet accumsan leo. Nunc auctor. Maecenas sollicitudin.\n" +
                "\n" +
                "Maecenas sollicitudin. Fusce nibh. Maecenas sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Aliquam id dolor. Suspendisse nisl. Maecenas libero. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Phasellus faucibus molestie nisl. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Pellentesque arcu. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Quisque porta. Aliquam ornare wisi eu metus. Fusce wisi. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam eget nisl. Fusce aliquam vestibulum ipsum.\n" +
                "\n" +
                "Praesent vitae arcu tempor neque lacinia pretium. Nullam faucibus mi quis velit. Ut tempus purus at lorem. Maecenas libero. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Quisque porta. Vivamus ac leo pretium faucibus. Aliquam ornare wisi eu metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean placerat. Maecenas sollicitudin. Integer malesuada. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.\n" +
                "\n" +
                "Curabitur sagittis hendrerit ante. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Suspendisse nisl. Nam quis nulla. Donec iaculis gravida nulla. Praesent id justo in neque elementum ultrices. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Aenean vel massa quis mauris vehicula lacinia. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla est. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Pellentesque sapien. Nunc dapibus tortor vel mi dapibus sollicitudin. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Integer pellentesque quam vel velit. Vestibulum fermentum tortor id mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla quis diam. Et harum quidem rerum facilis est et expedita distinctio.\n" +
                "\n" +
                "Etiam quis quam. Mauris metus. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Aliquam erat volutpat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Donec vitae arcu. Integer malesuada. Nullam dapibus fermentum ipsum. Et harum quidem rerum facilis est et expedita distinctio. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Donec iaculis gravida nulla. Donec vitae arcu. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Nullam eget nisl. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Pellentesque ipsum. Curabitur vitae diam non enim vestibulum interdum. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem.\n" +
                "\n" +
                "Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nullam faucibus mi quis velit. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Duis pulvinar. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Nullam dapibus fermentum ipsum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Aenean id metus id velit ullamcorper pulvinar. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus.\n" +
                "\n" +
                "Curabitur vitae diam non enim vestibulum interdum. Etiam quis quam. Donec vitae arcu. Nullam faucibus mi quis velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Proin mattis lacinia justo. Suspendisse nisl. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Duis pulvinar. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam faucibus mi quis velit.\n" +
                "\n" +
                "Pellentesque ipsum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Curabitur bibendum justo non orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur sagittis hendrerit ante. Nunc auctor. Nam sed tellus id magna elementum tincidunt. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Fusce aliquam vestibulum ipsum. Nam quis nulla. Integer tempor. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Phasellus faucibus molestie nisl. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Curabitur sagittis hendrerit ante. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Nulla est. Vivamus ac leo pretium faucibus.\n" +
                "\n" +
                "Etiam bibendum elit eget erat. Etiam egestas wisi a erat. Mauris elementum mauris vitae tortor. Maecenas lorem. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Aliquam erat volutpat. Nunc auctor. Praesent dapibus. In dapibus augue non sapien. Duis condimentum augue id magna semper rutrum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor.";
    }
}
